import type { Akun } from '../types'

// COA sesuai Excel: Update_Chart_Of_Account.xlsx
export const COA: Akun[] = [
  { kode:'1.1.1', nama:'Kas', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.2', nama:'Bank', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.3', nama:'Surat Berharga', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.4', nama:'Piutang Simpan Pinjam', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.5', nama:'Piutang Toko', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.6', nama:'Piutang Jasa Simpan Pinjam', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.7', nama:'Penyisihan Piutang Tak Tertagih', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.8', nama:'Persediaan Barang', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.9', nama:'Persediaan Lain-lain', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.10', nama:'Biaya dibayar dimuka', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.11', nama:'Pendapatan ymh diterima', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.12', nama:'Aset lancar lainnya', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.13', nama:'Penyertaan di PKPRI', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.1.14', nama:'Tabungan di PKPRI', kelompok:'Aset Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.1', nama:'Simpanan Berjangka', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.2', nama:'SKPB di PKPRI', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.5', nama:'Simpanan di koperasi sekunder', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.6', nama:'Properti investasi', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.7', nama:'Tanah', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.8', nama:'Bangunan', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.9', nama:'Mesin dan kendaraan', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.10', nama:'Inventaris', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'D' },
  { kode:'1.2.11', nama:'Akm. Penyusutan aset tetap', kelompok:'Aset Tidak Lancar', grup:'ASET', tipe:'K' },
  { kode:'2.1.1', nama:'Utang Usaha', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.2', nama:'Dana SHU Anggota (Jasa Simpanan)', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.3', nama:'Dana SHU Anggota (Jasa Pinjaman)', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.4', nama:'Dana Pengurus dan Pengawas', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.5', nama:'Dana Pendidikan', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.6', nama:'Dana Karyawan', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.7', nama:'Dana Sosial', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.8', nama:'Dana PDK (Pembangunan Daerah Kerja)', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.9', nama:'Simpanan Sukarela', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.10', nama:'Simpanan Wajib Khusus', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.11', nama:'Simpanan lain-lain', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.12', nama:'Biaya ymh dibayar', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.13', nama:'Dana Asuransi', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.1.14', nama:'Tabungan Hari Tua', kelompok:'Kewajiban Jk. Pendek', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.2.1', nama:'Utang Pajak', kelompok:'Kewajiban Jk. Panjang', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.2.2', nama:'Cadangan Risiko', kelompok:'Kewajiban Jk. Panjang', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.2.3', nama:'Simpanan berjangka', kelompok:'Kewajiban Jk. Panjang', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'2.2.4', nama:'Penyertaan modal', kelompok:'Kewajiban Jk. Panjang', grup:'KEWAJIBAN', tipe:'K' },
  { kode:'3.1.1', nama:'Simpanan Pokok', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'3.1.2', nama:'Simpanan Wajib', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'3.1.3', nama:'Hibah/ Donasi', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'3.1.4', nama:'Cadangan', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'3.1.5', nama:'SHU Tahun Lalu', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'3.1.6', nama:'SHU Periode Berjalan', kelompok:'Ekuitas', grup:'EKUITAS', tipe:'K' },
  { kode:'4.1.1', nama:'Pendapatan Jasa Pinjaman', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.2', nama:'Pendapatan Administrasi', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.3', nama:'Pendapatan Denda', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.4', nama:'Pendapatan Sewa', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.5', nama:'Penjualan Toko', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.6', nama:'Pendapatan konsinyasi', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.1.7', nama:'Retur penjualan', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'D' },
  { kode:'4.1.8', nama:'Pendapatan Lain-lain', kelompok:'Pendapatan Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'5.1.1', nama:'HPP Toko', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.2', nama:'Beban bunga Simpanan Sukarela', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.3', nama:'Beban penjualan', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.4', nama:'Beban Tunjangan Hari Raya/THR', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.5', nama:'Beban Honor karyawan', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.6', nama:'Beban Honor pengurus dan pengawas', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.7', nama:'Beban ATK', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.8', nama:'Beban sewa', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.9', nama:'Beban premi asuransi', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.10', nama:'Beban Peringatan Hari Koperasi dan Hari Besar Nasional', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.11', nama:'Beban Listrik, Telepon, Air', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.12', nama:'Beban Internet dan Aplikasi', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.13', nama:'Beban Lembur Pegawai, Pengurus dan pengawas', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.14', nama:'Beban Lembur Pengurus', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.15', nama:'Beban transport Pengurus dan Pengawas', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.16', nama:'Beban pendidikan karyawan', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.17', nama:'Beban Penyisihan piutang tak tertagih', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.18', nama:'Beban rapat organisasi', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.19', nama:'Beban pendidikan perkoperasian', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.20', nama:'Beban Rapat anggota', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.21', nama:'Beban perkoperasian (Izin Usaha dan Dokumen Lainnya)', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.22', nama:'Beban penyusutan dan amortisasi', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.1.23', nama:'Beban perkoperasian lainnya', kelompok:'Beban Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'4.2.1', nama:'Pendapatan bunga bank', kelompok:'Pendapatan Luar Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.2.2', nama:'Keuntungan penjualan aset tetap', kelompok:'Pendapatan Luar Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'4.2.3', nama:'Keuntungan di luar usaha lainnya', kelompok:'Pendapatan Luar Usaha', grup:'PENDAPATAN', tipe:'K' },
  { kode:'5.2.1', nama:'Beban administrasi bank', kelompok:'Beban Luar Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.2.2', nama:'Beban pajak bunga', kelompok:'Beban Luar Usaha', grup:'BEBAN', tipe:'D' },
  { kode:'5.2.3', nama:'Beban di luar usaha lainnya', kelompok:'Beban Luar Usaha', grup:'BEBAN', tipe:'D' },
]

// Helper: cari nama akun by kode (termasuk custom dari localStorage)
export function getAkunNama(kode: string): string {
  const std = COA.find(a => a.kode === kode)?.nama
  if (std) return std
  try {
    const custom: Akun[] = JSON.parse(localStorage.getItem('sia-koperasi-custom-coa') || '[]')
    return custom.find(a => a.kode === kode)?.nama ?? kode
  } catch { return kode }
}